### ISSUE TITLE
Failed to resolve dependency X. Cannot find module X. Require stack: List

### ISSUE THREAD

**Issue by homero304** [sergioramos/serverless-plugin-tree-shake#29]
Hi, i get the following messages when using the plugin.
serverless.yml file:
> ...
> package:
>  individually: true
>  excludeDevDependencies: false
> ...
> plugins:
> \- serverless-plugin-tree-shake
package.json file:
> ...
> "devDependencies": {
>    "aws-sdk": "^2.475.0",
>    "aws-sdk-mock": "^4.4.0",
>    "dirty-chai": "^2.0.1",
>    "generator-serverless-policy": "^3.1.0",
>    "serverless": "^1.43.0",
>    "serverless-domain-manager": "^4.2.0",
>    "serverless-iam-roles-per-function": "^1.0.4",
>    "serverless-mocha-plugin": "^1.12.0",
>    "serverless-plugin-tree-shake": "^1.1.1",
>    "serverless-tag-api-gateway": "^1.0.0",
>    "standard": "^11.0.1"
>  }
> ...
Terminal output:
> Serverless: Packaging service...
> Serverless: Failed to resolve dependency ./publisher:
> Cannot find module './publisher'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ./shared-ini:
> Cannot find module './shared-ini'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ../vendor/endpoint-cache:
> Cannot find module '../vendor/endpoint-cache'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ./publisher:
> Cannot find module './publisher'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ./shared-ini:
> Cannot find module './shared-ini'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ../vendor/endpoint-cache:
> Cannot find module '../vendor/endpoint-cache'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ./publisher:
> Cannot find module './publisher'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ./shared-ini:
> Cannot find module './shared-ini'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ../vendor/endpoint-cache:
> Cannot find module '../vendor/endpoint-cache'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ./publisher:
> Cannot find module './publisher'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ./shared-ini:
> Cannot find module './shared-ini'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ../vendor/endpoint-cache:
> Cannot find module '../vendor/endpoint-cache'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ./publisher:
> Cannot find module './publisher'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ./shared-ini:
> Cannot find module './shared-ini'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ../vendor/endpoint-cache:
> Cannot find module '../vendor/endpoint-cache'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ./publisher:
> Cannot find module './publisher'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ./shared-ini:
> Cannot find module './shared-ini'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ../vendor/endpoint-cache:
> Cannot find module '../vendor/endpoint-cache'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ./publisher:
> Cannot find module './publisher'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ./shared-ini:
> Cannot find module './shared-ini'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ../vendor/endpoint-cache:
> Cannot find module '../vendor/endpoint-cache'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ./publisher:
> Cannot find module './publisher'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ./shared-ini:
> Cannot find module './shared-ini'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ../vendor/endpoint-cache:
> Cannot find module '../vendor/endpoint-cache'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ./publisher:
> Cannot find module './publisher'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ./shared-ini:
> Cannot find module './shared-ini'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js
> Serverless: Failed to resolve dependency ../vendor/endpoint-cache:
> Cannot find module '../vendor/endpoint-cache'
> Require stack:
> \- /node_modules/serverless-plugin-tree-shake/index.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/classes/PluginManager.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/Serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/scripts/serverless.js
> \- /.nvm/versions/node/v12.0.0/lib/node_modules/serverless/bin/serverless.js

am i missing something?

Cheers,
Homero

**Comment by sergioramos** [comment]
thank you for the report. do you mind setting up a test case? a non-working example on a gist would be enough.

Also, are you suing typescript? if so, are you sure you're setting "main" to the typescript file rather than a build output?

**Comment by homero304** [comment]
Hi Sergio,
Sorry for the late response.
I am using javascript es6. I am deploying an http api in amazon aws with serverless framework. I get these messages during deployment and when i call a http api route.
Please find the source code in the following link https://github.com/homero304/serverless-plugin-tree-shake-hello-world

Cheers,
Homero

**Comment by homero304** [comment]
Most probably, i made a mistake. I could not find out where i messed up.
But, i found another solution. Thanks Sergio.

**Comment by sergioramos** [comment]
I did try your repo and it was working as expected, so I was trying to see what was wrong. I'm glad you figured it out 👍
